/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tskinnerjavaqaautomationtask;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ListObjectCallsTest {
    @Test void appHasAGreeting() {
        ListObjectCalls classUnderTest = new ListObjectCalls();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
